### ISSUE TITLE
Android example throws runtime error. 

### ISSUE THREAD

**Issue by tyler274** [EthicalML/vulkan-kompute#77]
in  `void OpTensorSyncDevice::init()`
```
for (std::shared_ptr<Tensor> tensor : this->mTensors) {
        if (!tensor->isInit()) {
            throw std::runtime_error("Kompute OpTensorSyncDevice: Tensor param "
                                     "has not been initialized");
        }
```

coming from `void KomputeModelML::train`
```
sq->record<kp::OpTensorSyncDevice>({ wIn, bIn });
```
in the app's code.

**Comment by axsaucedo** [comment]
Thank you for reporting this @tyler274 ! This is due to a change that was added this weekend to support asynchronous and parallel operations, namely  #75 and #73.

The fix for this is simple, and you have two options:
1. Running the example against release 0.3.2 (Which means just checking out that branch)
2. Add the same changes that were added in #75 to the logistic regression test (which uses the same code)

For option #2, you will need to run the tensor creation on a separate sequence. 

Namely, you have to change this part:

```cpp
        if (std::shared_ptr<kp::Sequence> sq =
                    mgr.getOrCreateManagedSequence("createTensors").lock()) {

            sq->begin();

            sq->record<kp::OpTensorCreate>(params);

            sq->end();
            sq->eval();

            // Record op algo base
            sq->begin();

            sq->record<kp::OpTensorSyncDevice>({ wIn, bIn });
```

To this:

```cpp
        {
             std::shared_ptr<kp::Sequence> sqTensor =
              mgr.createManagedSequence().lock();

            sqTensor->begin();
            sqTensor->record<kp::OpTensorCreate>(params);
            sqTensor->end();
            sqTensor->eval();

            std::shared_ptr<kp::Sequence> sq = mgr.createManagedSequence().lock();

            sq->begin();

            sq->record<kp::OpTensorCreate>(params);

            sq->end();
            sq->eval();

            // Record op algo base
            sq->begin();

            sq->record<kp::OpTensorSyncDevice>({ wIn, bIn });
```

This is something you can find in the `test/TestLogisticRegression.cpp` file.

For now, I recommend you to go for option 1 - I will update the examples now so they work with the recent 0.4.0 release.

**Comment by axsaucedo** [comment]
@tyler274 this now has been fixed in master, if you pull the latest you should be able to build - I just tested it with Android studio as well:
![image](https://user-images.githubusercontent.com/1447507/96546876-02bf6900-12a3-11eb-9722-0d48e7c64093.png)

I'll re-open issue to confirm it has been fixed on your side.

**Comment by tyler274** [comment]
Thanks I'll check out master in the morning.

**Comment by tyler274** [comment]
Works on master, thanks!

**Comment by axsaucedo** [comment]
Great - thanks for confirming @tyler274
